server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:oracle:thin:@192.168.8.141:1521:orcl
    username: system
    password: 123456
    hikari:
     connection-properties: oracle.jdbc.Trace=true;LogLevel=FINEST
upload:
  engFilePath: C:\\Users\\zhangxin\\Desktop\\SFO_FRR_Template_v10_eng_unlock.xlsm
  chiFilePath: C:\\Users\\zhangxin\\Desktop\\SFO_FRR_Template_v10_chi_unlock.xlsm

excelPath : C:/Users/zhangxin/Desktop/

IN_T_SL_FORM_NEWAPP: TypeOfApplication,DateOfReceiptOfApplication,CERefNo,Borrower,TypeOfLoan,Currency


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
